"""empty message

Revision ID: 44c6bd3d25b1
Revises: 
Create Date: 2018-11-28 10:44:10.443885

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '44c6bd3d25b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('GET', sa.Boolean(), nullable=True))
    op.add_column('permissions', sa.Column('POST', sa.Boolean(), nullable=True))
    op.add_column('permissions', sa.Column('PUT', sa.Boolean(), nullable=True))
    op.drop_column('permissions', 'read')
    op.drop_column('permissions', 'edit')
    op.drop_column('permissions', 'add')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('add', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('permissions', sa.Column('edit', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('permissions', sa.Column('read', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('permissions', 'PUT')
    op.drop_column('permissions', 'POST')
    op.drop_column('permissions', 'GET')
    # ### end Alembic commands ###
